### PR TITLE
Remove additional dimension in single-patch extraction.

### LINKED ISSUE #145: Wrong shape in training data generation
Hi everyone,

Just found a bug in the training data generation if only one patch per image is extracted. These two lines
* https://github.com/juglab/n2v/blob/2ff781bf32c298f151bb26630e03ef45c3230c8f/n2v/internals/N2V_DataGenerator.py#L240
* https://github.com/juglab/n2v/blob/2ff781bf32c298f151bb26630e03ef45c3230c8f/n2v/internals/N2V_DataGenerator.py#L253
Lead to a wrong shape.

For 2 patches per image we would get (2, 256, 256, 1), but for 1 patch per image we get (1, 1, 256, 256, 1). Adding the extra `[np.newaxis]` is the issue.

### PR DESCRIPTION
**Pull request by tibuch**
Closes #145.

### CODE REVIEW

**Comment by tibuch** [comment]
@jdeschamps I don't know who would be responsible to review this change.

**Comment by jdeschamps** [comment]
Sounds good!

**Comment by tibuch** [comment]
Any chance we can get a quick release for this bug-fix? :innocent:

**Comment by tibuch** [comment]
:partying_face: thanks!

**Comment by jdeschamps** [comment]
> Any chance we can get a quick release for this bug-fix? 😇

On its way 😄

**Comment by tibuch** [comment]
You are the best!

**Comment by jdeschamps** [comment]
It is up!

**Pull request merged**
